pipeline {
    agent any

    stages {
        stage('clone project') {
            steps {
                // Automatically checks out the branch that triggered the build
                //checkout scm
                git branch : 'master',
url : 'https://github.com/sharathg97/Amazon.git'
            }
        }

        stage('clean') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean'
                }
            }
        }
    stage('compile') {
            steps {
                dir('Amazon') {
                    sh 'mvn compile'
                }
            }

    }

   stage('test') {
      steps {
dir('Amazon') {

           sh 'mvn test'
}
       }
   }
   stage('build') {
      steps {
dir('Amazon') {

           sh 'mvn clean install'
}
       }
   }
  }
  }
